// Auto-generated by scripts/scrape-engnovate-reading.py — do not edit.
import type { IeltsReadingTest } from "../../types/ielts"

import cambridge_ielts_21_reading_test_2 from "./cambridge-ielts-21-reading-test-2.json"
import cambridge_ielts_21_reading_test_3 from "./cambridge-ielts-21-reading-test-3.json"
import cambridge_ielts_21_reading_test_4 from "./cambridge-ielts-21-reading-test-4.json"

export const LOCAL_READING_TESTS: Record<string, IeltsReadingTest> = {
  "cambridge-ielts-21-reading-test-2": cambridge_ielts_21_reading_test_2 as IeltsReadingTest,
  "cambridge-ielts-21-reading-test-3": cambridge_ielts_21_reading_test_3 as IeltsReadingTest,
  "cambridge-ielts-21-reading-test-4": cambridge_ielts_21_reading_test_4 as IeltsReadingTest,
}
